// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRySlDRAxCUV-lCVX3IV454oxgic3zviE',
    appId: '1:496424988002:web:2b7d4dd4c7c0555ccf103b',
    messagingSenderId: '496424988002',
    projectId: 'exam-db668',
    authDomain: 'exam-db668.firebaseapp.com',
    storageBucket: 'exam-db668.appspot.com',
    measurementId: 'G-W11LZ6M9VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98e7pX6w0fTcTaM5xBWGwQ_weYyZkCUQ',
    appId: '1:496424988002:android:8bf28402750d8087cf103b',
    messagingSenderId: '496424988002',
    projectId: 'exam-db668',
    storageBucket: 'exam-db668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57fUXDEfaSQPz1Ul4gHgkEXPMVd6QVE8',
    appId: '1:496424988002:ios:e3d6f9ca37669327cf103b',
    messagingSenderId: '496424988002',
    projectId: 'exam-db668',
    storageBucket: 'exam-db668.appspot.com',
    androidClientId: '496424988002-dedd03911p0votmuh270bvaio5qp72ji.apps.googleusercontent.com',
    iosClientId: '496424988002-kge6pep0hhn6apv06rcunqnug9j89nv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57fUXDEfaSQPz1Ul4gHgkEXPMVd6QVE8',
    appId: '1:496424988002:ios:e3d6f9ca37669327cf103b',
    messagingSenderId: '496424988002',
    projectId: 'exam-db668',
    storageBucket: 'exam-db668.appspot.com',
    androidClientId: '496424988002-dedd03911p0votmuh270bvaio5qp72ji.apps.googleusercontent.com',
    iosClientId: '496424988002-kge6pep0hhn6apv06rcunqnug9j89nv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
